apiVersion: v1
kind: Service 
metadata:
  name: application-service 
  namespace: application-namespace 
spec:
  selector: 
    app: app 
  ports:
    - name: http 
      port: 8000
      protocol: TCP 
--- 

apiVersion: v1
kind: Deployment 
metadata:
  name: application-deployment 
  namespace: application-namespace 
spec:
  template:
    metadata:
      labels: 
        app: app 
    spec:
      containers:
        - name: frontend-application
          image: crazycoderrr/custom_table_editor 
          ports:
            - name: http 
              port: 3000
              protocol: TCP 
          imagePullPolicy: IfNotPresent 
--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-map
  namespace: application-namespace 
data:
  APPLICATION_HOST: localhost
  APPLICATION_PORT: 8000
